# Generated by Django 4.2.7 on 2024-03-13 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='media/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', '.webp'])]),
        ),
        migrations.AlterField(
            model_name='report',
            name='images',
            field=models.ManyToManyField(blank=True, to='communication.image'),
        ),
        migrations.AlterField(
            model_name='report',
            name='videos',
            field=models.ManyToManyField(blank=True, to='communication.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='media/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi'])]),
        ),
    ]
